#!/usr/bin/env python
# -*- coding:utf-8 -*-

# We need the module 'sys' to print text to stdout.

import sys


# Dictionary of the primers they have at GATC (Forward and Reverse)

GATC_Primers = {'pJet1-FP': 'ACTACTCGATGAGTTTTCGG', 'pcDNA3.1-RP/1': 'CAAACAACAGATGGCTGGC', 'pGFP-FP': 'GAGTTTGTAACAGCTGCTG', 'T7minus1': 'AATACGACTCACTATAGGG', 'pEGFP-RP': 'AACAGCTCCTCGCCCTTG', 'pVL2': 'GACGCACAAACTAATATCAC', 'pGL2': 'TCTTTATGTTTTTGGCGTC', 'pVL1': 'GGGTTTAACATTACGGATTTC', 'pGL3-1': 'GAGCTGACTGGGTTGAAG', 'pESP-RP': 'TCCAAAAGAAGTCGAGTGG', 'pEGFP_C2-RP': 'TTTAAAGCAAGTAAAACCTC', 'GFPN1-5': 'GAGCTCAAGCTTCGAATTC', 'pGBT9-RP': 'CGTTTTAAAACCTAAGAGTCAC', 'pGEX3-RP': 'TCAAGAATTATACACTCCG', 'SP6': 'ATTTAGGTGACACTATAGAA', 'pTYB-FP': 'GGAAGACGATTATTATGGG', 'PCR1': 'CGGGCCTCTTCGCTATT', 'PCR2': 'TTAGCTCACTCATTAGG', 'GLprimer1': 'TGTATCTTATGGTACTGTAACTG', 'pACT2-RP': 'CAGTTGAAGTGAACTTGC', 'Topo-1': 'TCGGATCCACTAGTAACG', 'Topo-2': 'GTGTGATGGATATCTGC', 'pJet1-RP': 'TGAGGTGGTTAGCATAGTTC', 'BAC2': 'CCCAGTCACGACGTTGTAAAAC', 'BAC1': 'GCTCGTATGTTGTGTGGAATTG', '35S-B': 'AGTGGAAAAGGAAGGTGGCT', 'BGH-Reverse': 'TAGAAGGCACAGTCGAGG', 'KAN2-RP': 'GCAATGTAACATCAGAGATTTTGAG', 'pGL3-RV3': 'CTAGCAAAATAGGCTGTCC', 'pREP-FP': 'GCTCGATACAATAAACGCC', 'pDONOR-FP': 'TAACGCTAGCATGGATCTC', 'pACT2-FP': 'GATGATGAAGATACCCCAC', 'pET-RP': 'CTAGTTATTGCTCAGCGG', 'pIRES-RP': 'TATAGACAAACGCACACCG', 'pBR1': 'CGAAAAGTGCCACCTGAC', 'pBR2': 'GGAGCCACTATCGACTAC', 'pBR3': 'TCCCCATCGGTGATGTC', 'SK': 'CGCTCTAGAACTAGTGGATC', 'M13-FP': 'TGTAAAACGACGGCCAGT', 'pMT-FP': 'CATCTCAGTGCAACTAAAG', 'pEGFP_C2-FP': 'GATCACATGGTCCTGCTG', 'pcDNA1.1-RP/1': 'TAGAATCAGTAGTTTAACAC', 'pTrcHis-FP': 'GACCGGAATTATCGATTAAC', 'pGBT9-FP': 'AGTGCGACATCATCATCG', 'pRSET-RP': 'ATGCTAGTTATTGCTCAGC', 'T7-981079': 'TAATACGACTCACTATAG', 'pRH-RP': 'CAAAATTCAATAGTTACTATCGC', 'SeqYeast 18S': 'XXXX', 'pc3.1GFP-Topo-RP': 'CCCATTAACATCACC', 'pTI2-1-1': 'GGCAAATATTCTGAAATGAGC', 'pTI2-1-2': 'GCGTTTCACTTCTGAGTTCG', 'TET-1 RP-1': 'TAAATTGCACTGAAATCTAGAAATA', 'pTeSp-1': 'CCTCCATAGAAGACACC', 'pTeSp-2': 'GCCCTGCCACTCATCG', '1492r': 'TACGGYTACCTTGTTACGACTT', 'pET30er-FP': 'TCATCATTCTTCTGGTCTG', 'pBakPAC-FP': 'TAAAATGATAACCATCTCGC', 'pcDNA3.1-FP': 'CTCTGGCTAACTAGAGAAC', 'pUC-R': 'TGCCTGCAGGTCGACTCTAG', 'pTal-FP': 'CGGGAGGTACTTGGAGCG', 'pEGFP-FP': 'TTTAGTGAACCGTCAGATC', 'pUC-F': 'GCCAGTGAATTCGAGCTCGG', 'SeqGP 16S  ': 'XXXX', 'pGEX-3': 'GGAGCTGCATGTGTCAGAG', 'pEGFP-N': 'CCGTCCAGCTCGACCAG', 'pQE-RP-50': 'CTAGCTTGGATTCTCACC', 'Topo-2N': 'AGATGCATGCTCGAGCGG', 'pET36b-FP': 'GCTAAATTCGAACGCCAG', '16S-1392r': 'ACGGGCGGTGTGTRC', 'TET-1 FP-1': 'GGGTGCGCATGATCCTCTAGAGT', 'SeqGN 16S': 'XXXX', 'pET-24a': 'GGGTTATGCTAGTTATTGCTCAG', 'pBacPAC-RP': 'GTCTGTAAATCAACAACGC', 'EBV-RP': 'GTGGTTTGTCCAAACTCATC', 'KS': 'TCGAGGTCGACGGTATC', 'PBR4': 'CTCGGCACCGTCACC', "3'-Gal 4": 'GAACTTGCGGGGTTTTTC', 'pVP22-FP': 'CGCTTCTCGCCCCAGAC', 'PCR1minus1': 'GGGCCTCTTCGCTATT', 'EGF2': 'GGGGATGTGCTGCAAGG', 'PolyC-D': 'CCCCCCCCCCCCD', 'pTrcHis-RP': 'CTGATTTAATCTGTATCAGG', 'EGF1': 'CCAAGCTATTTAGGTGACAC', 'pQE-RP': 'GTTCTGAGGTCATTACTGG', 'pQE-FP': 'CGGATAACAATTTCACACAG', 'CMV-F': 'CGCAAATGGGCGGTAGGCGTG', 'RPC': 'ACAGCTATGACCATGATTACG', 'UP-40': 'GTTTTCCCAGTCACGAC', '35S-A': 'AAGGGTCTTGCGAAGGATAG', 'PolyA-B': 'AAAAAAAAAAAAAAAAAAAAAAAB', 'pGEX5-FP': 'AACGTATTGAAGCTATCCC', 'pDONOR-RP': 'GCAATGTAACATCAGAGAT', 'T7': 'TAATACGACTCACTATAGGG', 'KAN2-FP': 'ACCTACAACAAAGCTCTCATCAACC', 'T3': 'ATTAACCCTCACTAAAGGGA', 'LPP1': 'ATACGACTCACTATAGGGAGAC', 'LPP2': 'ACAAATTGGACTAATCGATGGC', 'UP-2': 'CGTTGTAAAACGACGGCC', 'pETBlue-RP': 'AATAGCTTTAATGCGGTAG', 'pRSET-RPnew': 'GGGTTATGCTAGTTATTGC', 'pGEX-5': 'CTGGCAAGCCACGTTTGG', 'TriplEx5`LD': 'GAAGCGCGCCATTGTGTTGG', 'pMalE': 'TCAGACTGTCGATGAAGC', 'pcDNA1.1-RP': 'CTCTGTAGGTAGTTTGTCC', 'M13-RP': 'CAGGAAACAGCTATGACC', 'pRH-FP': 'CTGTCTCTATACTCCCCTATAG', 'PolyT-V': 'TTTTTTTTTTTTTTTTTTTTTV', 'pBAD-FP': 'ATGCCATAGCATTTTTATCC', '16S-27f': 'AGAGTTTGATCMTGGCTCAG'}


#def Search_primer()
''' Sequence of the vector(str) -> Name of the primer to chose in GATC Website(str)
    This function searchs in the vector sequence for a primer (from some vector in GATC)
    and returns the name of vector primer to chose and the nº of sequenced nt after the primer
'''

# Give sequence of vector to test in txt. Tried with With open(sys.argv[1]) but got only the first match (?)


with open(sys.argv[1]) as f:
     vector = f.read()
for Primer, Sequence in GATC_Primers.iteritems():
    if Sequence in vector:
        if 'RP' in Primer:
            print 'CAUTION! This is a reverse primer' # Need more elegance in output
            print Primer
            print Sequence
	    print '--------'
        
        else: 
              print Primer
              print Sequence
	      print '--------'

# Use f.seek() for comparing distances to insert	
